name: la_mode
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.13
  provider: ^6.1.2
  persistent_bottom_nav_bar: ^5.0.2
  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  ###----firebase----####
  #cloud_firestore: ^4.15.7
  ###----3D----####
  model_viewer_plus: ^1.7.0
  dio: ^5.4.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pin_code_fields: ^8.0.1
  quickalert: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

###----Change Icon App----###
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/la_mode_logo.png"
  web:
    generate: true
    image_path: "assets/images/la_mode_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/password/
    - assets/images/dialog/
    - assets/images/categories/
    - assets/images/collections/
    - assets/images/decoration/
    - assets/images/on_board/
    - assets/images/empty/
    - assets/icons/
    - assets/icons/media/
    - assets/translations/
    - assets/3d/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
