// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ybojO0FP18hB-1OGzS5DWph-mEhOiCY',
    appId: '1:875645807484:web:25cb352f729760809d52f9',
    messagingSenderId: '875645807484',
    projectId: 'la-mode-418300',
    authDomain: 'la-mode-418300.firebaseapp.com',
    storageBucket: 'la-mode-418300.appspot.com',
    measurementId: 'G-MTKBE43CBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzhpGSB51M2GZgXq6ZCgXJkdcsUWyfbpE',
    appId: '1:875645807484:android:34ec8f47455296de9d52f9',
    messagingSenderId: '875645807484',
    projectId: 'la-mode-418300',
    storageBucket: 'la-mode-418300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6IYq9OdWx9pf2obBupTFvtl0knP5lAT4',
    appId: '1:875645807484:ios:4c6f6d340f0c4e019d52f9',
    messagingSenderId: '875645807484',
    projectId: 'la-mode-418300',
    storageBucket: 'la-mode-418300.appspot.com',
    iosBundleId: 'com.pepars.myEcommerceApp',
  );
}
