// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDBGxMhYXOGN_d9et1jFI4P8Q4bfOUp-CI',
//     appId: '1:223718398582:web:5a974f686edcc49ec25d57',
//     messagingSenderId: '223718398582',
//     projectId: 'la-mode-1a23d',
//     authDomain: 'la-mode-1a23d.firebaseapp.com',
//     storageBucket: 'la-mode-1a23d.appspot.com',
//     measurementId: 'G-RX3Q6NM511',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD7LaDCx50HUlXsgpNReGx1lU6ex42YCJs',
//     appId: '1:223718398582:android:b7acf93f20dd0aa5c25d57',
//     messagingSenderId: '223718398582',
//     projectId: 'la-mode-1a23d',
//     storageBucket: 'la-mode-1a23d.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDFMCeVo86O6F2tNlIKB-Qvus9BaYgQ7oI',
//     appId: '1:223718398582:ios:2ae52c8c8299533cc25d57',
//     messagingSenderId: '223718398582',
//     projectId: 'la-mode-1a23d',
//     storageBucket: 'la-mode-1a23d.appspot.com',
//     iosBundleId: 'com.example.myEcommerceApp',
//   );
// }
